name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: sudo apt-get update && sudo apt-get install -y lcov gcovr

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.14

    - name: Configure project
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

  coverage:
    name: Coverage (Linux only)
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4

    - name: Install gcovr
      run: sudo apt-get update && sudo apt-get install -y gcovr

    - name: Configure with coverage flags
      run: |
        cmake -S . -B build \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="--coverage" \
              -DCMAKE_C_FLAGS="--coverage"

    - name: Build with coverage
      run: cmake --build build

    - name: Run tests (continue even if some fail)
      run: ctest --test-dir build || true

    - name: Generate HTML coverage report
      run: |
        mkdir -p build/coverage
        gcovr -r . --html --html-details \
              --output build/coverage/coverage.html \
              -e main/ \
              -f Lab/ \
              -f Lab/tests/

    - name: Upload HTML coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage/coverage.html
