name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests (binary only, filter in main.cpp)
        run: |
          if [ -f ./build/gTest_test ]; then
            ./build/gTest_test
          elif [ -f ./build/Release/gTest_test.exe ]; then
            ./build/Release/gTest_test.exe
          elif [ -f ./build/Release/gTest_test ]; then
            ./build/Release/gTest_test
          else
            echo "Test binary not found!"
            exit 1
          fi

  coverage:
    name: Coverage (Ubuntu only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcovr lcov

      - name: Configure with coverage flags
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build project
        run: cmake --build build

      - name: Run tests (binary only, filter in main.cpp)
        run: ./build/gTest_test || true
        continue-on-error: true

      - name: Generate HTML coverage report
        if: always()
        run: gcovr -r . --html --html-details -o build/coverage.html

      - name: Upload HTML coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage.html
